### PR TITLE
Request: Herring management Areas

### PR DESCRIPTION
**Pull request by andybeet**
Requesting the shapefile depicting the Herring Management Areas are added to NEFSCSpatial. The following files have been added as requested:

Saved data as sf object in an .rda file located in data/Herring_Management_Areas.rda
Documented data in R/Herring_Management_Areas.R (may need more metadata)
Ran roxygen2 to create .Rd file from documentation in man/Herring_Management_Areas.Rd
Updated reference in _pkgdown.yml

### CODE REVIEW

**Comment by andybeet** [comment]
@jmhatch one more after this. NEUS epu shapefile. Wont get to that until later in the week. Then we should brainstorm as to what else needs to get included

**Comment by jmhatch** [comment]
Looked good, @andybeet! I think the NEUS EPUs are already in there, @kimberly-bastille added them some time ago (NEFSCspatial::epu_sf). Or maybe you're referring to something different?

**Comment by andybeet** [comment]
@jmhatch we are missing documentation for it, mainly the source. Was thinking of changing the name too

**Comment by jmhatch** [comment]
@andybeet I see. I didn't even check if it had documentation. That sounds good.

**Pull request merged**
