### PR TITLE
Add weas

### PR DESCRIPTION
**Pull request by jmhatch**
@andybeet & @kimberly-bastille Could you both review this pull request?

## New Data

* I added BOEM active and planned wind energy areas (WEAs), which I've been using a lot lately.
* Accompanying R script in data-raw to create the rda
* Supporting files in boem folder in data-raw
* Added link to boem data set in pkgdown yml

## Text file changes

 I fixed some minor things (update README to reflect transfer to NEFSC and suppressed messages in an .Rmd vignette). 

* URL changes in `DESCRIPTION` file and `pkgdown.yml`
* Package install documentation changes in `Readme.md`
* Added list of contacts
* Updated gitleaks action in `secretScan.yml`

### CODE REVIEW

**Comment by andybeet** [comment]
@kimberly-bastille @jmhatch Ignore my pull request. This might cover it all. If not we'll adapt this

**Comment by jmhatch** [comment]
@andybeet @kimberly-bastille I don't mind at all @andybeet that you edited the main pull request description text. Looks good!

> There are also 36 fields in this sf object. Should we be explaining what they are?

There should be 23 fields, I think `sf::st_union` did something undesirable. I switched over to using `rbind` to combine the two feature layers into 1 `sf` object (thanks for catching that). But this is a good question. Maybe we can flesh this out at the next R Shiny meeting? I was just passing along all the fields provided in the raw data (by the data provider). But it doesn't look like all those fields are explained on BOEM's website (I didn't look that hard TBH, so the explanations may be there), so maybe we should pare the fields down to ones that are self-explanatory and easy to describe in the documentation (or easy to intuit what they are)?

> Not sure i understand what this data is from the documentation. If i follow the source link the first thing i see is a link to shapefiles (which is a zip file containing 4 shapefiles), none of which are what this is (at least i dont think so)

You can download a geodatabase (as a zip file) or the shapefiles (as a zip file). They should contain the same data. I extracted 2 of the 4 feature layers (not sure what to call elements of a geodatabase) from the geodatabase, combined them, and saved that as a rda file. The other 2 feature layers I'm not currently interested in (so I didn't include those). There are 4 feature layers in the geodatabase, just like the zip of shapefiles.

**Comment by andybeet** [comment]
ok, so i think if others want to use this data set, then they should really know what this product is since it really isnt anything right off the BOEM site. I think this can be dealt with in the documentation of the data set. I think we, as a group, need to determine what the data documentation should be listing. Agreed: next shiny meeting conversation

**Comment by andybeet** [comment]
@kimberly-bastille looks ok to me.

**Comment by kimberly-bastille** [comment]
Sorry for the delay. I agree I think it should be a conversation at the next shiny meeting. WEA, in general, should probably be discussed as they are rapidly changing but a data product that a lot of people will be using as wind work continues.

**Comment by jmhatch** [comment]
We decided not to include WEAs at the moment. Closing.

**Pull request closed without merging**
