### PR TITLE
Add leaflet maps to pkgdown site

### LINKED ISSUE #49: amapps_grid from raster to sf
The `raster` pkg in R depends on `sp`, which depends on `maptools`, `rgdal`, and `rgeos`. The latter 3 pkgs will be retired soon (by October 2023). I need to transfer the `amapps_grid` data from `raster` to `terra`. Unfortunately, there are issues with saving `SpatRaster` objects from `terra` using `save` (which is the method used by `usethis::use_data`). As a workaround, I'm going to save `amapps_grid` as an `sf` object with an example of how to convert the `sf` object into a `SpatRaster` object.

This is ugly, but should work. At least until I can figure out if and how to save `SpatRaster` objects in `*.rda` files.

### PR DESCRIPTION
**Pull request by jmhatch**
Resolves #49 and #50.

For now, leaflet maps need to be built locally to avoid having to re-build them every time the pkgdown site is re-built and re-deployed (it takes some time). Could change this in the future w/ a GitHub action. The leaflet maps and corresponding *.Rmd files are generated using `data-raw/create_leaflet_maps.R`. The leaflet maps are stored in `pkgdown/leaflet_maps` as *.rda files. The *.Rmd files are stored in `vignettes/articles`. Also, added a `Maps` element to the navbar with a drop-down menu pointing to the corresponding *.Rmd file with the leaflet map (which gets rendered to html when the site is built). Some datasets would not render on leaflet in a web browser, I'm guessing it's too much data (they often have very fine coastline data). Below is a list of data sets that are not included in `Maps` b/c of the leaflet issue:
1. amapps_grid
2. Herring_Management_Areas
3. NAFO_Divisions_2021_poly_clipped
4. Statistical_Areas_2010
5. Statistical_Areas_2010_withNames

### CODE REVIEW

**Comment by andybeet** [comment]
@jmhatch This looks great. Nice job. Regarding the other data sets, i'll take a look at 2-5. I know the stat areas are unnecessarily large. And yes it is due to the coastline being overly detailed
 
@kimberly-bastille if you like this then merge the request

**Comment by jmhatch** [comment]
Thanks, @andybeet. What's weird is that I can get those large datasets to render on leaflet in RStudio's Viewer. But when I try to render the html in a web browser, like Chrome, it fails and gives an error message in the log console. Not sure what to make of it.

**Comment by andybeet** [comment]
@jmhatch Can you add the script to data raw showing how you created the rds files in the pkgdown folder? I am trying to see if i get the same issue as you do with the other data sets but unsure how to create those files that you call in the rmds

**Comment by jmhatch** [comment]
@andybeet, sorry about that. I thought they would get added, since they don't meet any of the `.gitignore` exclusion rules. But when I ran `git status --ignored` I saw a couple of files in `data-raw/` that were being ignored. Weird. If you know what would cause this or if I'm doing something wrong let me know. I just added the files using `git add -f [path-to-file]`. Should be in the `data-raw` folder now in the `add_leaflet` branch.

**Comment by andybeet** [comment]
@jmhatch I was able to render all other datasets to html using your method (other than amapps). It does take some time to build website, but i'm not sure that is such a big deal. The gh action will only run when merging branches to main. However when building locally it will be an annoyance. Is that what you meant/found? Was that why you didnt want to add them to the repo?

**Comment by jmhatch** [comment]
Thanks @andybeet. So when you run `pkgdown::build_site()` and navigate to `Maps/Herring_Management_areas` (or one of the other troublemakers) in your web browser you see a leaflet map? I tried again and it still fails.  Maybe it's a Chrome (or specific version of Chrome) issue?

**Comment by jmhatch** [comment]
Thanks @andybeet. It must be a local issue, so that's good to know. Could you tell me what web browser (and version) you're using? Also, could you create a PR for your branch to fold in those extra leaflet maps to `main`?

**Comment by andybeet** [comment]
I am using chrome Version 115.0.5790.171 (Official Build) (64-bit).
I will create a pull request now

**Comment by jmhatch** [comment]
Thanks @andybeet, appreciate it. I am using the same Chrome version, so I'm thinking it might be an R / R pkg version issue.

**Pull request merged**
