### PR TITLE
Adding requested GSC Restricted Area and LMA1

### LINKED ISSUE #21: [Request]: LMA1 Restricted Area
### Contact details

andrew.beet@noaa.gov

### What data would you like to add?

This dataset depicts the boundaries of the Lobster Management Area One Restricted Area (Maine) in effect annually from October 1 to January 30.

### Are there data currently in the package that are similar?

- [X] I have searched the existing data.

### Can you provide a URL to view the data online?

https://www.fisheries.noaa.gov/resource/map/lma-1-restricted-area

### What is the type of data?

Shapefile

### If Other, please specify data type

_No response_

### Does this data require any additional manipulation before usage?

No

### LINKED ISSUE #22: [Request]: Great South channel Restricted area
### Contact details

andrew.beet@noaa.gov

### What data would you like to add?

This dataset depicts the boundaries of the Great South Channel Restricted Area (East of Cape Cod, MA) in effect from April 1 to June 30 annually

### Are there data currently in the package that are similar?

- [X] I have searched the existing data.

### Can you provide a URL to view the data online?

https://www.fisheries.noaa.gov/resource/map/great-south-channel-restricted-area

### What is the type of data?

Shapefile

### If Other, please specify data type

_No response_

### Does this data require any additional manipulation before usage?

No

### PR DESCRIPTION
**Pull request by jmhatch**
@andybeet requested the shapefiles depicting the LMA1 and GSC Restricted Areas be added to NEFSCSpatial. The following files have been added as requested:

1. R code to download, process, and save the shapefiles are in `data-raw/get_nmfs_remote_sf.R`
2. Saved data as `sf` objects in `.rda` files located in `data/LMA1_Restricted_Area_FR.rda` and `data/Great_South_Channel_Restricted_Trap_Pot_Area.rda`
3. Documented data in `R/data_LMA1_Restricted_Area_FR.R` (may need more metadata) and `R/data_Great_South_Channel_Restricted_Trap_Pot_Area.R` (may need more metadata)
4. Ran `roxygen2` to create `.Rd` files from documentation in `man/LMA1_Restricted_Area_FR.Rd` and `man/Great_South_Channel_Restricted_Trap_Pot_Area.Rd`
5. Updated `reference` in `_pkgdown.yml` to include LMA1 and GSC

I updated `data-raw/create_sf_data_from_url.R` to replace hyphens with underscores in the exported data object name, since hyphens can cause issues  loading data objects (which I didn't realize until now).

Resolves #21 and #22.

### CODE REVIEW

**Comment by jmhatch** [comment]
Trying out another one! I'll leave the last request for someone else.

**Comment by jmhatch** [comment]
@andybeet That's my mistake. I must of branched off of my branch, when I meant to branch off of main.  We could try to merge both PR #24 and then this PR and see what happens. Or just close PR #24 and then merge this PR? I'm fine with whatever. I'll try not to branch off of branches in the future :sweat_smile:.

**Comment by andybeet** [comment]
@jmhatch ok so lets merge this one. i just added both issues to this PR. We can then just close 24.
@kimberly-bastille is too busy right now so let's just try and get this workflow down and she can jump on board when her plate is less full

**Comment by jmhatch** [comment]
@andybeet Sounds good, and thanks for doing that!

**Pull request merged**
